apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: RedPlanetHQcore

resources:
# Configuration
- configmap.yaml
- secrets.yaml
- clickhouse-configmap.yaml

# Storage
- persistent-volume-claims.yaml

# Databases (StatefulSets)
- postgres-statefulset.yaml
- neo4j-statefulset.yaml
- clickhouse-statefulset.yaml

# Supporting services
- redis-deployment.yaml

# Services
- services.yaml

# Trigger.dev components
- trigger-init-deployment.yaml
- trigger-electric-deployment.yaml
- trigger-webapp-deployment.yaml
- trigger-supervisor-deployment.yaml

# CORE application
- core-deployment.yaml

# Ingress
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: core
  app.kubernetes.io/version: "0.1.24"

patchesStrategicMerge:
# Add any patches here if needed

# Example for customizing values without modifying the original files:
# patches:
# - patch: |-
#     - op: replace
#       path: /spec/replicas
#       value: 3
#   target:
#     kind: Deployment
#     name: core-app