apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: RedPlanetHQcore
  labels:
    app.kubernetes.io/name: core
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard # Adjust based on your cluster

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
  namespace: RedPlanetHQcore
  labels:
    app.kubernetes.io/name: core
    app.kubernetes.io/component: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard # Adjust based on your cluster

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: RedPlanetHQcore
  labels:
    app.kubernetes.io/name: core
    app.kubernetes.io/component: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard # Adjust based on your cluster