export const GatewayErrorCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",
  FOLDER_NOT_FOUND: "FOLDER_NOT_FOUND",
  FOLDER_SCOPE_DENIED: "FOLDER_SCOPE_DENIED",
  PATH_OUTSIDE_FOLDER: "PATH_OUTSIDE_FOLDER",
  CAPABILITY_DISABLED: "CAPABILITY_DISABLED",
  TIMEOUT: "TIMEOUT",
  INTERNAL: "INTERNAL",
} as const;
export type GatewayErrorCode = typeof GatewayErrorCode[keyof typeof GatewayErrorCode];
